<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <AssemblyName>Plain.Core</AssemblyName>
    <RootNamespace>Plain.Core</RootNamespace>
  </PropertyGroup>
</Project>
